### ISSUE TITLE
Toast with React Query - Loading State Toast is not removed

### ISSUE THREAD

**Issue by chrisLovesCode** [theodorusclarence/expansion-pack#11]
Hi,
i implemented the Toasts RQ with your script and curl.
when visiting the example page toast-rq i notided the submit button keeps in loading/spinner state. I expected the code and so far it looks like there are still toasts with "loading" type in the toast state, even when the loading is done.

So current fix looks like this:
`
//useRQWithToast.tsx

    if (isError) {
      toast.error(toastMessage.error, { id: toastStatus.current });
      toastStatus.current = 'done';
    } else if (isLoading) {
      toastStatus.current = toast.loading(toastMessage.loading, { id: toastStatus.current });
    } else if (isSuccess) {
      toastStatus.current = toast.success(toastMessage.success, { id: toastStatus.current });
    } else if (data) {
      toast.success(toastMessage.success, { id: toastStatus.current });
      toastStatus.current = 'done';
    }
`

this way "it works" but there still stays an toast in the state with status "idle" but it does not affect the ui.. but doesnt feel good 
After all i'm wondering if this bug is already noticed? or maybe i implemented something wrong? i'm wondering since script and instruction are realy clear

**Comment by chrisLovesCode** [comment]
PS: btw, since im new to react query: i noticed t, when changing tabs/refocus page tab, a new query is fired. is this normal behaviour? since it seems to unnecesarry increase requests on apis

**Comment by theodorusclarence** [comment]
Thanks for the issue, we'll check the code soon
